#vc_fact_ip: "10.93.60.143"
#vc_fact_hostname: "nested-devqevcenter"
#vc_fact_nameserver: '["10.93.60.129"]'
#vc_fact_gateway: "10.93.60.129"
vc_fact_domain: "vsphere.local"
vc_fact_ntp: "10.0.77.54"
#vc_fact_password: "{{ lookup('community.general.random_string', length=16, spedevqeal=True) }}"
vc_fact_password: "{{ lookup('ansible.builtin.env', 'VCESXIPASSWORD') }}"
vc_fact_datacenter1: "nested-devqedatacenter-1"
vc_fact_datacenter2: "nested-devqedatacenter-2"
vc_fact_cluster1: "nested-devqecluster-1"
vc_fact_cluster2: "nested-devqecluster-2"
vc_fact_deployment_network: "segment-884-ipv4-6-nested"
vc_fact_deployment_network2: "segment-884-ipv4-6-nested"
# below is for nested and is the real vCenter to deploy the nested vc to
vc_hostname: "{{ lookup('ansible.builtin.env', 'MAINVCHOSTNAME') }}"
vc_username: "{{ lookup('ansible.builtin.env', 'MAINVCUSERNAME') }}"
vc_password: "{{ lookup('ansible.builtin.env', 'MAINVCPASSWORD') }}"

vc_datacenter: "devqedatacenter-1"
vc_cluster: "devqecluster-1"
vc_folder: "nested-limited"
